use std::path::PathBuf;

use rayon::prelude::*;

use crate::changed_files::ChangedFilesScope;
use crate::mdlint_policy::MdLintPolicy;
use crate::{discover, editorconfig, formatting, symlink, ui};
use prim_fmt::{FileKind, Style};

pub(super) type FormattedFile = (PathBuf, FileKind, Style, MdLintPolicy, String, String);

/// What one discovery-and-format pass produced.
pub(super) struct Loaded {
    /// The files prim owns, each paired with its formatted form.
    pub(super) files: Vec<FormattedFile>,
    /// A named path could not be read or parsed (exit `2`). A failed write is
    /// the caller's to add: it happens after this pass.
    pub(super) had_error: bool,
    /// Every path prim was pointed at was skipped, so nothing was examined
    /// (FR-4.4c). The gate modes report it as an error; the writing modes
    /// treat it as the no-op it is.
    pub(super) examined_nothing: bool,
}

#[derive(Debug, PartialEq, Eq)]
enum LoadMessageKind {
    Warning,
    Error,
}

#[derive(Debug, PartialEq, Eq)]
struct LoadMessage {
    kind: LoadMessageKind,
    text: String,
}

enum LoadOutcome {
    /// Boxed because a `FormattedFile` is a six-tuple carrying a `PathBuf`, a
    /// `FileKind`, a `Style`, an `MdLintPolicy` and two `String`s, which makes
    /// it far larger than the other two variants; every `LoadOutcome` would
    /// otherwise be sized for it. The
    /// tuple already owns several heap allocations, so one more per formatted
    /// file costs nothing measurable next to reading and formatting it.
    Formatted(Box<FormattedFile>),
    Message(LoadMessage),
    Skipped,
}

pub(super) fn load_and_format(
    paths: &[PathBuf],
    excludes: &[String],
    ignores: discover::IgnoreSettings,
    changed_files_scope: &ChangedFilesScope,
) -> Result<Loaded, discover::Error> {
    let discovery = discover::collect(paths, excludes, ignores, changed_files_scope)?;
    for ignored in &discovery.ignored {
        let message = match ignored.reason {
            discover::IgnoreReason::Primignore => format!(
                "{}: matched by .primignore; skipped (use --no-primignore to process it)",
                ignored.path.display()
            ),
            discover::IgnoreReason::Generated(tool) => format!(
                "{}: generated by {tool}; skipped (prim formats authored files, use --no-primignore to process it)",
                ignored.path.display()
            ),
        };
        ui::warning(&message);
    }
    let outcomes = load_discovered(discovery.files);
    let (results, messages, had_error) = summarize_outcomes(outcomes);
    emit_messages(&messages);
    Ok(Loaded {
        files: results,
        had_error,
        examined_nothing: discovery.examined_nothing,
    })
}

fn load_discovered(files: Vec<discover::Discovered>) -> Vec<LoadOutcome> {
    files
        .into_par_iter()
        .map_init(editorconfig::Resolver::new, |resolver, file| {
            load_one(resolver, file)
        })
        .collect()
}

fn load_one(resolver: &mut editorconfig::Resolver, file: discover::Discovered) -> LoadOutcome {
    // A symlink is a path type prim does not own (FR-4.6, AD-0016). Following
    // one would destroy it: the atomic write of FR-6.4 is a temp file plus
    // rename, which replaces the link with a regular file and leaves the file
    // it pointed at still drifting (#166).
    //
    // Only a named path is tested. `walk_into` admits an entry only where
    // `ft.is_file()`, and the `ignore` walker does not follow links, so a walk
    // never offers one — which is exactly why the named route has to decline
    // it too, or `prim fmt --check .` and `prim fmt --check <link>` answer the
    // same question differently (AD-0009). Testing only the named route keeps
    // the extra `lstat` off the per-file walk path.
    if file.explicit && symlink::is_symlink(&file.path) {
        return warning(symlink::skipped(&file.path));
    }

    let Some(kind) = prim_fmt::classify(&file.path) else {
        return if file.explicit {
            if file.path.exists() {
                warning(format!(
                    "{}: not a file type prim formats; skipped",
                    file.path.display()
                ))
            } else {
                error(format!("{}: no such file", file.path.display()))
            }
        } else {
            LoadOutcome::Skipped
        };
    };

    let original = match std::fs::read_to_string(&file.path) {
        Ok(text) => text,
        Err(err) => {
            let message = format!("{}: {err}", file.path.display());
            return if file.explicit {
                error(message)
            } else {
                warning(message)
            };
        }
    };

    let style = resolver.resolve(&file.path);
    let formatted =
        match formatting::contained(&file.path, || prim_fmt::format(kind, &original, &style)) {
            Ok(Ok(text)) => text,
            Ok(Err(err)) => {
                let message = format!("{}: {err}", file.path.display());
                return if file.explicit {
                    error(message)
                } else {
                    warning(message)
                };
            }
            // A dependency panicked. Always an error, walked or named: unlike an
            // unparseable file, this is prim's bug and never the caller's, so it
            // is not something a walk should pass over quietly (AD-0017).
            Err(_) => return error(formatting::panic_message(&file.path)),
        };

    let markdown_policy = if kind == FileKind::Markdown {
        resolver.resolve_mdlint_policy(&file.path)
    } else {
        MdLintPolicy::default()
    };

    LoadOutcome::Formatted(Box::new((
        file.path,
        kind,
        style,
        markdown_policy,
        original,
        formatted,
    )))
}

fn summarize_outcomes(outcomes: Vec<LoadOutcome>) -> (Vec<FormattedFile>, Vec<LoadMessage>, bool) {
    let mut had_error = false;
    let mut messages = Vec::new();
    let mut results = Vec::new();

    for outcome in outcomes {
        match outcome {
            LoadOutcome::Formatted(file) => results.push(*file),
            LoadOutcome::Message(message) => {
                had_error |= message.kind == LoadMessageKind::Error;
                messages.push(message);
            }
            LoadOutcome::Skipped => {}
        }
    }

    (results, messages, had_error)
}

fn emit_messages(messages: &[LoadMessage]) {
    for message in messages {
        match message.kind {
            LoadMessageKind::Warning => ui::warning(&message.text),
            LoadMessageKind::Error => ui::error(&message.text),
        }
    }
}

fn warning(text: String) -> LoadOutcome {
    LoadOutcome::Message(LoadMessage {
        kind: LoadMessageKind::Warning,
        text,
    })
}

fn error(text: String) -> LoadOutcome {
    LoadOutcome::Message(LoadMessage {
        kind: LoadMessageKind::Error,
        text,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use rayon::ThreadPoolBuilder;
    use std::fs;
    use std::path::Path;

    fn write(path: &Path, contents: &str) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, contents).unwrap();
    }

    fn write_bytes(path: &Path, contents: &[u8]) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, contents).unwrap();
    }

    fn uneven_json(item_count: usize) -> String {
        let items = (0..item_count)
            .map(|index| format!("\"item-{index}\""))
            .collect::<Vec<_>>()
            .join(",");
        format!("{{\"items\":[{items}]}}\n")
    }

    fn file_names(results: &[FormattedFile]) -> Vec<String> {
        results
            .iter()
            .map(|file| file.0.file_name().unwrap().to_string_lossy().into_owned())
            .collect()
    }

    #[test]
    fn formatted_results_preserve_discovery_order_with_uneven_work_sizes() {
        let dir = tempfile::tempdir().unwrap();
        write(&dir.path().join("b.json"), &uneven_json(8));
        write(&dir.path().join("a.json"), &uneven_json(2_000));
        write(&dir.path().join("c.json"), &uneven_json(40));

        let discovered = discover::collect(
            &[dir.path().to_path_buf()],
            &[],
            discover::IgnoreSettings::default(),
            &ChangedFilesScope::All,
        )
        .unwrap()
        .files;
        let expected = discovered
            .iter()
            .map(|file| {
                file.path
                    .file_name()
                    .unwrap()
                    .to_string_lossy()
                    .into_owned()
            })
            .collect::<Vec<_>>();

        let outcomes = ThreadPoolBuilder::new()
            .num_threads(4)
            .build()
            .unwrap()
            .install(|| load_discovered(discovered));
        let (results, messages, had_error) = summarize_outcomes(outcomes);

        assert_eq!(file_names(&results), expected);
        assert!(messages.is_empty());
        assert!(!had_error);
    }

    #[test]
    fn load_messages_preserve_discovery_order_for_warnings_and_errors() {
        let dir = tempfile::tempdir().unwrap();
        let missing = dir.path().join("b.json");
        write_bytes(&dir.path().join("a.json"), &[0xFF, 0xFE, 0x00, 0x01]);

        let discovered = discover::collect(
            &[dir.path().to_path_buf(), missing.clone()],
            &[],
            discover::IgnoreSettings::default(),
            &ChangedFilesScope::All,
        )
        .unwrap()
        .files;
        let outcomes = ThreadPoolBuilder::new()
            .num_threads(4)
            .build()
            .unwrap()
            .install(|| load_discovered(discovered));
        let (_results, messages, had_error) = summarize_outcomes(outcomes);

        assert!(had_error);
        assert_eq!(messages.len(), 2);
        assert_eq!(messages[0].kind, LoadMessageKind::Warning);
        assert!(
            messages[0]
                .text
                .starts_with(&format!("{}:", dir.path().join("a.json").display()))
        );
        assert_eq!(messages[1].kind, LoadMessageKind::Error);
        assert!(
            messages[1]
                .text
                .starts_with(&format!("{}:", missing.display()))
        );
    }
}
